development:
  secret_key_base: key
  stripe_secret_key: 'pk_test_51MGQRCCbQ0LAP6KFWlVvYIEziOWmcPvu7w2l2CeTAUCOOTknQgTJ4CjzmLwpy6PUcG9puDPZZROLSUyXAlwWBUSS00FpRhhuN1'
  stripe_publishable_key: 'sk_test_51MGQRCCbQ0LAP6KF2sK5HbfF8fOFeaT6yHBLa51W2yti8uBVOPO9uR5W4sfSRXL8tnuUWLiQLgRPQZJH2unEbwXm00OLFdvkkT'

#production:
#  stripe_secret_key: 'sk_live_aLvPhyGtUwlLSHvms3KhCdrL'
#  stripe_publishable_key: 'pk_live_nbTqsm8Gg0eHGrQVRbWnjlyN'